In [1]:
from aoc import results, read_txt, remove_empty, load_text
import numpy as np

In [128]:
day = 'day14'
text = load_text(day, num = 0)

Result of Advent of Code, year 2023, day 14
Find description at https://adventofcode.com/2023/day/14

input\day14_example.txt


In [129]:
text

['O....#....',
 'O.OO#....#',
 '.....##...',
 'OO.#O....O',
 '.O.....O#.',
 'O.#..O.#.#',
 '..O..#O..O',
 '.......O..',
 '#....###..',
 '#OO..#....']

In [130]:
def tilt_array(array):
    array_string = ''.join(array)
    splitted = array_string.split('#')
    final_list = []
    for sub in splitted:
        sub_list = [*sub]
        sub_list.sort(reverse=True)
        final_list.append(''.join(sub_list))
    final_string = '#'.join(final_list)
    final_array = np.array([*final_string])
    return final_array

In [131]:
def to_array(m):
    mlist = []
    for mi in m:
        mlist.append([*mi])

    return np.asarray(mlist)

In [133]:
to_array(board)

array([['.', '.', '.', '.', '.', '#', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '#', '.', '.', '.', 'O', '#'],
       ['.', '.', '.', '.', '.', '#', '#', '.', '.', '.'],
       ['.', '.', 'O', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', 'O', 'O', 'O', '#', '.'],
       ['.', 'O', '#', '.', '.', '.', 'O', '#', '.', '#'],
       ['.', '.', '.', '.', 'O', '#', '.', '.', '.', 'O'],
       ['.', '.', '.', '.', '.', '.', '.', 'O', 'O', 'O'],
       ['#', '.', '.', '.', 'O', '#', '#', '#', '.', 'O'],
       ['#', '.', 'O', 'O', 'O', '#', '.', '.', '.', 'O']], dtype='<U1')

In [134]:
def flip_north(board):
    board_tilted = []
    for array in board.T:
        board_tilted.append(tilt_array(array))
    board_final = np.array(board_tilted).T

    return board_final

In [135]:
def flip_cycle(board):


    for i in range(4):
        board = flip_north(board)
        board = np.rot90(board, k = 3)

    return board

board = to_array(text)

In [156]:
board = to_array(text)

In [158]:
def cal_load(board):
    h, w = board.shape
    val_array = np.flip((np.arange(1, h + 1) * np.ones((h, w))).T)

    total = np.sum((board == 'O') * val_array)
    total = int(total)
    return total


In [189]:
reps = 100
t = np.zeros(reps)
old_sum = np.inf
for i in range(reps):
    board_final = flip_cycle(board)
    new_sum = np.sum(board_final != board)
    new_load = cal_load(board_final)
    t[i] = new_load
    if np.sum(t == new_load) > 5:
        a = np.where(t==new_load)[0]
        r = a[2:] - a[1:-1]
        if len(set(r)) == 1:
            break
    else:
        board = board_final
        old_sum = new_sum

In [198]:
t

array([69., 65., 64., 65., 63., 68., 69., 69., 65., 64., 65., 63., 68.,
       69., 69., 65., 64., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65.])

In [193]:
x = 7
a1 = t[-x:]
a2 = t[-2*x:-x]

In [197]:
a2

array([65., 65., 65., 65., 65., 65., 65.])

In [194]:
a1

array([65., 65., 65., 65., 65., 65., 65.])

In [196]:
a

array([ 1,  3,  8, 10, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99], dtype=int64)

In [192]:
t[-7:]

array([69., 65., 64., 65., 63., 68., 69., 69., 65., 64., 65., 63., 68.,
       69., 69., 65., 64., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65., 65.,
       65., 65., 65., 65., 65., 65., 65., 65., 65.])

In [191]:
a

array([ 1,  3,  8, 10, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99], dtype=int64)

In [190]:
r

array([5, 2, 5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [188]:
a

array([ 0,  1,  7,  8, 14, 15], dtype=int64)

In [187]:
r

array([6, 1, 6, 1], dtype=int64)

In [186]:
t

array([69., 69., 65., 64., 65., 63., 68., 69., 69., 65., 64., 65., 63.,
       68., 69., 69.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [177]:
a

array([0, 1, 7], dtype=int64)

In [176]:
r

array([6], dtype=int64)

In [171]:
new_load == t

array([ True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [170]:
a

array([ 0,  1,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64)

In [169]:
r

array([6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [167]:
a[2:] - a[1:-1]

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], dtype=int64)

In [165]:
a

(array([ 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99],
       dtype=int64),)

In [154]:
old_sum = np.inf
for i in range(50):
    board_final = flip_cycle(board)
    new_sum = np.sum(board_final != board)
    print(new_sum)
    if new_sum and old_sum != new_sum:
        board = board_final
        old_sum = new_sum
    else:
        break

if (1000000000 - i )% 2:
    board = flip_cycle(board)


30
8
2
2


In [155]:
i

3

1

In [ ]:
if 10

In [147]:
i

1

In [148]:
new_sum

2

In [149]:
old_sum

2

In [139]:
board == board_final

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True]])

In [140]:
board_final

array([['.', '.', '.', '.', '.', '#', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '#', '.', '.', '.', 'O', '#'],
       ['.', '.', '.', '.', '.', '#', '#', '.', '.', '.'],
       ['.', '.', 'O', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', 'O', 'O', 'O', '#', '.'],
       ['.', 'O', '#', '.', '.', '.', 'O', '#', '.', '#'],
       ['.', '.', '.', '.', 'O', '#', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', 'O', 'O', 'O', 'O'],
       ['#', '.', '.', '.', 'O', '#', '#', '#', '.', 'O'],
       ['#', '.', 'O', 'O', 'O', '#', '.', '.', '.', 'O']], dtype='<U1')

In [141]:
board

array([['.', '.', '.', '.', '.', '#', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '#', '.', '.', '.', 'O', '#'],
       ['.', '.', '.', '.', '.', '#', '#', '.', '.', '.'],
       ['.', '.', 'O', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', 'O', 'O', '#', '.'],
       ['.', 'O', '#', '.', '.', '.', 'O', '#', '.', '#'],
       ['.', '.', '.', '.', 'O', '#', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', 'O', 'O', 'O', 'O'],
       ['#', '.', '.', '.', 'O', '#', '#', '#', '.', 'O'],
       ['#', '.', 'O', 'O', 'O', '#', '.', '.', 'O', 'O']], dtype='<U1')

In [138]:
board_final = flip_cycle(board)

In [ ]:
boa

In [ ]:
board = to_array(text); board

In [ ]:
for i in range(100):
    board_final = flip_cycle(board)
    print(np.sum(board != board_final))
    board = board_final


In [ ]:
board

In [ ]:
board = board_final

In [ ]:
board_final

In [ ]:
board

In [ ]:

board = to_array(text)
for i in range(4):
    board_tilted = []
    for array in board.T:

        board_tilted.append(tilt_array(array))
    board = np.array(board_tilted).T
    board = np.rot90(board)

In [ ]:
q = to_array(text)

In [ ]:
board == q

In [ ]:
q

In [ ]:
board

In [ ]:
board.shape

In [ ]:
np.rot90(board)

In [ ]:
def get_value(text, second):
    board = to_array(text)

    if second:
        for i in range(1000000000):
            board_final = flip_cycle(board)
            if np.equal(board, board_final):
                break
            else:
                board = board_final
    else:
        board_final = flip_north(board)


    h, w = board_final.shape
    val_array = np.flip((np.arange(1, h + 1) * np.ones((h, w))).T)

    total = np.sum((board_final == 'O') * val_array)
    total = int(total)

    return total

In [ ]:
def to_array(m):

    mlist = []
    for mi in m:
        mlist.append([*mi])

    return np.asarray(mlist)
def tilt_array(array):
    array_string = ''.join(array)
    splitted = array_string.split('#')
    final_list = []
    for sub in splitted:
        sub_list = [*sub]
        sub_list.sort(reverse = True)
        final_list.append(''.join(sub_list))
    final_string = '#'.join(final_list)
    final_array = np.array([*final_string])
    return final_array


In [ ]:
board = to_array(text)

board_tilted = []
for array in board.T:
   board_tilted.append(tilt_array(array))
board_final = np.array(board_tilted).T

h, w = board_final.shape
val_array = np.flip((np.arange(1,h + 1) * np.ones((h,w))).T)

total = np.sum((board_final == 'O') * val_array)


In [ ]:
h, w = board_final.shape
val_array = np.flip((np.arange(1,h + 1) * np.ones((h,w))).T)

In [ ]:
np.ones((h,w))


In [ ]:
val_array = np.flip((np.arange(1,h + 1) * np.ones((h,w))).T)

In [ ]:
val_array

In [ ]:
board_final

In [ ]:
a = q.split('#')

In [ ]:
p = a[0]

In [ ]:
v = [*p]

In [ ]:
v.sort(reverse = True)

In [ ]:
tilt_array(l)

In [ ]:

l

In [ ]:
v

In [ ]:
v

In [ ]:
for p in a:
    t = [*p].sort()


In [ ]:
m[:, 0]

# day 13

In [ ]:
day = 'day13'
text = load_text(day, num = 0)

In [ ]:
def split_maps(text):
    all = []
    cur = []
    for line in text:
        if line == '':
            all.append(cur.copy())
            cur = []
        else:
            cur.append(line)
    all.append(cur)
    return all

def to_array(m):

    mlist = []
    for mi in m:
        mlist.append([*mi])

    return np.asarray(mlist)
def vertical_mirror(ti_map):
    idx = 0
    h,w = ti_map.shape
    for i in range(2,h-1):


        left = np.flip(ti_map[:i,:], axis = 0)
        right = ti_map[i:,:]

        hl, wl = left.shape
        hr, wr = right.shape

        if hl > hr:
            m = hr
        else:
            m = hl

        # print('left:', left[:,:m])
        # print('right:',right[:,:m])
        if np.array_equal(left[:m,:], right[:m, :]):
            idx = i
        #ti_map[:i] == np.flip(ti_map[i:np.min([i+i, h)])
    return idx * 100
def horizontal_mirror(ti_map):
    idx = 0
    h,w = ti_map.shape
    for i in range(2,w-1):


        left = np.flip(ti_map[:,:i], axis = 1)
        right = ti_map[:,i:]

        hl, wl = left.shape
        hr, wr = right.shape

        if wl > wr:
            m = wr
        else:
            m = wl

        # print('left:', left[:,:m])
        # print('right:',right[:,:m])
        if np.array_equal(left[:,:m], right[:, :m]):
            idx = i
            print(left[:,:m], right[:, :m])
        #ti_map[:i] == np.flip(ti_map[i:np.min([i+i, h)])
    return idx

In [ ]:
text = load_text(day, num = 1)

In [ ]:
a = np.ones((10,10))
b = np.ones((10,5))
if not b.shape > a.shape:
    a[b.shape]

In [ ]:
a

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
a.shape > b.shape

In [ ]:
a

In [ ]:
b

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
a = torch.tensor(np.random.randint(5,8, (20,20))*.1)

In [ ]:
q = F.normalize(a)

In [ ]:
(a - a.mean())/a.std()

In [ ]:
q.max()

In [ ]:
q.min()

In [ ]:
text

In [ ]:
maps = split_maps(text)
total = 0
for m in maps:
    ti_map = to_array(m)
    val = vertical_mirror(ti_map)
    val += horizontal_mirror(ti_map)
    total += val

In [ ]:
m

In [ ]:
m = maps[2]
ti_map = to_array(m)
print(vertical_mirror(ti_map))
print(horizontal_mirror(ti_map))

In [ ]:
m

In [ ]:

total

In [ ]:
total

In [ ]:
text

In [ ]:
def get_sets(p):
    string = ''.join(p)
    q = str(string).split('.')
    lens = [len(qi) for qi in q if len(qi) != 0]
    return lens


def rec(p, n,qms,  c):
    global tdict

    if c != len(qms):
        gsets =get_sets(p[:qms[c]])
        #print(gsets, p[:qms[c]])
        if str(gsets) + ',' + str(c)in tdict.keys():
            if c != 0:
                return tdict[str(gsets) + ',' + p[qms[c-1]] + ',' + str(c)]
            else:
                return tdict[str(gsets) + ',' + str(c)]
        else:
            t1 = p.copy()
            t1[qms[c]] = '#'
            t2 = p.copy()
            t2[qms[c]] = '.'

            a1 = rec(t1, n,qms, c+1)
            a2 = rec(t2, n,qms, c+1)
            val = a1 + a2
            if c!= 0:
                key = str(gsets) + ',' + p[qms[c-1]] + ',' + str(c)
            else:
                key = str(gsets) + ',' + str(c)
            tdict[key] = val
            return val
    else:
        if np.array_equal(np.array(get_sets(p)), n):
            key = str(get_sets(p)) + ',' + p[qms[c-1]] + ',' + str(c)
            tdict[key] = 1
            return 1
        else:
            key = str(get_sets(p)) + ',' + p[qms[c-1]] + ',' + str(c)
            tdict[key] = 0
            return 0

def get_line_val(line, second):
    global tdict
    tdict = {}

    v, n = line.split(' ')
    n = np.asarray(n.split(',')).astype(int)
    if second:
        v = '?'.join([v] * 5)

    n = list(n) * 5 if second else list(n)
    qms = np.where(np.array([*v]) == '?')


    total = rec(np.array([*v]), n, qms[0], 0)


    return total


def get_value(text, second):
    val = np.sum([get_line_val(line, second) for line in text])

    return val

In [ ]:
get_line_val(line, 0)

In [ ]:
get_value(text, 0)

In [ ]:
tdict

In [ ]:
aline

In [ ]:
line

In [ ]:
tdict

In [ ]:
dict

In [ ]:
line = text[0]; line

In [ ]:
tdict

Keep

In [ ]:
def hyperlink_markdown(path, done, begin = 1, end = 26):

    hyperlinks = ''

    for num in range(begin, end):
        if num in done:
            hyperlinks += f'[**]({path}{num:02d}.py) |'
        else:
            hyperlinks += f'[X]({path}{num:02d}.py) |'

    return hyperlinks

path = 'https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day'
hyperlink_markdown(path, done = [1,2,3,4,6,7], begin = 1, end = 26)

In [ ]:
def table_formatter(begin = 1, end = 26):

    table_line = ''
    for  i in range(begin, end):
        table_line += f':-----:|'

    return table_line

table_formatter(1, 26)

In [ ]:
import os
import shutil

In [ ]:
os.listdir()

In [ ]:
src = 'day13.py'
for i in range(14,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [ ]:
src = 'day01.py'
for i in range(8,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_example.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_example.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_input.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_input.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)