In [2]:
from aoc import results, read_txt, remove_empty
import os
from glob import glob
import numpy as np

In [3]:
day = 'day10'

path = f'input/{day}'

files = glob(f'{path}*')
file = files[0]


In [8]:
right = np.array([0,1]).reshape((2,1))
left = np.array([0,-1]).reshape((2,1))
up = np.array([-1,0]).reshape((2,1))
down = np.array([1,0]).reshape((2,1))


In [25]:
def next_pos(maze, pos, step):
    h,w = maze.shape
    new_pos = pos + step
    if new_pos[0] < 0 or new_pos[0] >= h or new_pos[1] < 0 or new_pos[1] >= w:
        return None

    return maze[new_pos[0], new_pos[1]], new_pos

def start_dir(maze, start_pos):



    p, pos = next_pos(maze, start_pos, right)
    if p == '-' or p =='J' or p == '7':
        return 'right'
    p, pos = next_pos(maze, start_pos, right)
    if p == '-' or p =='L' or p == 'F':
        return 'left'
    p, pos = next_pos(maze, start_pos, right)
    if p == '|' or p =='L' or p == 'J':
        return 'up'
    p, pos = next_pos(maze, start_pos, right)
    if p == '|' or p =='F' or p == '7':
        return 'down'

def next_dir(maze, pos, d):
    if d == 'right':
        p, pos_next = next_pos(maze, pos, right)
        if p == 'S':
            next_d = 'start'
        elif p == '-':
            next_d = 'right'
        elif p == 'J':
            next_d = 'up'
        elif p == '7':
            next_d = 'down'
    if d == 'left':
        p, pos_next = next_pos(maze, pos, left)
        if p == 'S':
            next_d = 'start'
        elif p == '-':
            next_d = 'left'
        elif p == 'F':
            next_d = 'down'
        elif p == 'L':
            next_d = 'up'
    if d == 'up':
        p, pos_next = next_pos(maze, pos, up)
        if p == 'S':
            next_d = 'start'
        elif p == '|':
            next_d = 'up'
        elif p == '7':
            next_d = 'left'
        elif p == 'F':
            next_d = 'right'
    if d == 'down':
        p, pos_next = next_pos(maze, pos, down)
        if p == 'S':
            next_d = 'start'
        elif p == '|':
            next_d = 'down'
        elif p == 'J':
            next_d = 'left'
        elif p == 'L':
            next_d = 'right'
    return pos_next, next_d

In [28]:
def get_value(file, second):
    text = read_txt(file)
    maze = np.array([[*l] for l in text])

    pos = np.array(np.where(maze == 'S'))
    d = start_dir(maze, pos)
    step = 0
    while d != 'start':
        pos, d = next_dir(maze, pos, d)
        step +=1
    return step//2


In [30]:
step

8

In [24]:
next_dir(maze, start_pos, 'right')

(array([[1],
        [2]], dtype=int64),
 'right')

In [75]:
p, pos = next_pos(maze, start_pos, left)
if p == '-' or p =='L' or p == 'F':
    if p1:
        p1 = pos
        p1dir = 'r'

In [76]:

p, pos = next_pos(maze, start_pos, up)
if p == '|' or p =='L' or p == 'J':
    print('up')

In [77]:

 p, pos = next_pos(maze, start_pos, down)
if p == '|' or p =='F' or p == '7':
    print('down')



down


In [61]:
maze

array([['.', '.', '.', '.', '.'],
       ['.', 'F', '-', '7', '.'],
       ['.', '|', '.', '|', '.'],
       ['.', 'L', '-', 'J', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

In [49]:
next_
maze[start_pos[0], start_pos[1]]

array(['F'], dtype='<U1')

In [26]:
start_pos.shape

(2, 1)

In [28]:
start_pos + np.array([0,1]).T

array([[1, 2],
       [1, 2]], dtype=int64)

In [16]:
maze = np.array([[*l] for l in text])

In [15]:
np.array(maze)

array([['.', '.', '.', '.', '.'],
       ['.', 'F', '-', '7', '.'],
       ['.', '|', '.', '|', '.'],
       ['.', 'L', '-', 'J', '.'],
       ['.', '.', '.', '.', '.']], dtype='<U1')

In [7]:
q = get_val(l)

In [5]:

aa
qa
q.reverse()

AttributeError: 'numpy.int32' object has no attribute 'reverse'

In [105]:
t

5

In [85]:
text

['0 3 6 9 12 15', '1 3 6 10 15 21', '10 13 16 21 30 45']

In [84]:
line

array([10, 13, 16, 21, 30, 45])

In [89]:
day = 'day08'
path = f'input/{day}_'
files = glob(f'{path}*')
for second_part in range(2):
    for file in files:
        1 +1

In [90]:
file

'input\\day08_input.txt'

In [91]:
def read_map(file):
    text = read_txt(file)
    dirs = text[0]
    maps = text[2:]

    maps_list = {}
    for m in maps:
        map_split = m.split('=')
        maps_list[map_split[0].strip()] = [map_split[1].split(',')[0].strip()[1:],
                                           map_split[1].split(',')[1].strip()[:-1]]

    return dirs, maps_list


def calculate_steps(file, second):
    dirs, maps = read_map(file)
    dest_map = next(iter(maps))
    steps = 0
    while dest_map != 'ZZZ':
        print(dest_map, maps[dest_map])
        dest_map = maps[dest_map][(dirs[steps % len(dirs)] == 'R')]
        steps += 1
    return steps


In [92]:
dirs, maps = read_map(file)

In [96]:
len(maps.keys())

714

In [97]:
len(set(maps.keys()))

714

In [88]:
calculate_steps(file, 1)

AAA ['BBB', 'CCC']
CCC ['ZZZ', 'GGG']


2

In [ ]:


def get_value(None):
    return None

results(get_value, day)

In [15]:
from glob import glob
day = 'day08'
path = f'input/{day}_'
glob(f'{path}*')

['input\\day08_example1.txt',
 'input\\day08_example2.txt',
 'input\\day08_input.txt']

In [1]:
def hyperlink_markdown(path, done, begin = 1, end = 26):

    hyperlinks = ''

    for num in range(begin, end):
        if num in done:
            hyperlinks += f'[**]({path}{num:02d}.py) |'
        else:
            hyperlinks += f'[X]({path}{num:02d}.py) |'

    return hyperlinks

path = 'https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day'
hyperlink_markdown(path, done = [1,2,3,4,6,7], begin = 1, end = 26)

'[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day01.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day02.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day03.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day04.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day05.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day06.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day07.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day08.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day09.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day10.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day11.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day12.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day13.py) |[X](https://github

In [2]:
def table_formatter(begin = 1, end = 26):

    table_line = ''
    for  i in range(begin, end):
        table_line += f':-----:|'

    return table_line

table_formatter(1, 26)

':-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|'

In [8]:
import os
import shutil

In [9]:
os.listdir()

['aoc',
 'day01.py',
 'day04.py',
 'day05.ipynb',
 'day05.py',
 'day06.py',
 'day07.py',
 'input',
 'notebook.ipynb']

In [10]:
src = 'day01.py'
for i in range(2,4):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [11]:
src = 'day01.py'
for i in range(8,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [12]:
src = 'input/day01_example.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [13]:
src = 'input/day01_example.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [14]:
src = 'input/day01_input.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)

In [15]:
src = 'input/day01_input.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)