In [142]:
from aoc import results, read_txt, remove_empty
import os
from glob import glob
import numpy as np

In [186]:
day = 'day11'

path = f'input/{day}'

files = glob(f'{path}*')
file = files[0]


In [187]:
text = read_txt(file)
text = np.array([[*l] for l in text])

In [151]:
btext = text == '.'
h, w = btext.shape
cols = []
for i in range(h):
    if np.sum(btext[i, :]) == w:
        cols.append(i)
rows = []
for i in range(w):
    if np.sum(btext[:, i]) == h:
        rows.append(i)


In [208]:
def dists(text, rep = 3):
    btext = text == '.'
    h, w = btext.shape
    cols = []
    rows = []

    for i in range(h):
        if np.sum(btext[i, :]) == w:
            cols.append(i)

    for i in range(w):
        if np.sum(btext[:, i]) == h:
            rows.append(i)

    ntext = np.ones(text.shape)

    for i in range(h):
        if np.sum(btext[i, :]) == w:
            ntext[i,:] = rep

    for i in range(w):
        if np.sum(btext[:, i]) == h:
            ntext[:,i] = rep


    return ntext#.astype(int)

In [190]:
def get_coords(where):
    coords = []
    for x,y in zip(where[0], where[1]):
        coords.append([x,y])
    return coords

In [191]:
hashtags = np.where(text == '#')
coords = get_coords(hashtags)

In [192]:
coords

[[0, 3], [1, 7], [2, 0], [4, 6], [5, 1], [6, 9], [8, 7], [9, 0], [9, 4]]

In [170]:
q = dists(text, rep = 10)

In [197]:
total = 0
for i, c1 in enumerate(coords):
    for j, c2 in enumerate(coords[i + 1:]):
        break
    break

In [206]:
def calc_dist(c1, c2, q):
    xi = [c1[0], c2[0]]
    yi = [c1[1], c2[1]]
    xi.sort()
    yi.sort()

    v = np.sum(q[xi[0]:xi[1], c1[1]])
    v += np.sum(q[c2[0], yi[0]:yi[1]])
    return v

In [207]:
calc_dist(c1, c2, q)

[1]
[ 1  1 10  1]
14
[0, 1] [3, 7]


In [198]:
c1

[0, 3]

In [199]:
c2

[1, 7]

In [193]:
coords

[[0, 3], [1, 7], [2, 0], [4, 6], [5, 1], [6, 9], [8, 7], [9, 0], [9, 4]]

In [182]:
text

array([['.', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['.', '#', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '#', '.', '.', '.', '.', '.']], dtype='<U1')

In [ ]:
def get_total_distance2(coords, q):
    total = 0
    for i, c1 in enumerate(coords):
        for j, c2 in enumerate(coords[i + 1:]):
            total += calc_dist(c1, c2, q)
    return total


In [ ]:
for c

In [89]:
btext = text == '.'
h, w = btext.shape
idx = []

for i in range(h):
    if np.sum(btext[i, :]) == w:
        idx.append(i)
q = text.copy()
rep = 5
for i in range(rep):
    q = np.insert(q, idx, np.repeat(np.reshape(q[idx[0], :], (1,w)), 1, axis = 0), axis=0)

In [90]:
q

array([['.', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '#', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'

In [77]:
q

array([['.', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['.', '#', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '#', '.', '.', '.', '.', '.']], dtype='<U1')

In [25]:
adef expand(text, columns = True, c = '.'):
    btext = text == '.'
    h, w = btext.shape
    idx = []
    if columns:
        for i in range(h):
            if np.sum(btext[i, :]) == w:
                idx.append(i)
        text = np.insert(text, idx, text[idx[0], :], axis=0)
    else:
        for i in range(w):
            if np.sum(btext[:, i]) == h:
                idx.append(i)
        text = np.insert(text, idx, np.reshape(text[:, idx[0]], (h,1)), axis=1)
    return text



In [43]:
gal = expand(expand(text, columns = True), columns = False)

In [44]:


hashtags = np.where(gal == '#')
for i, (x, y) in enumerate(np.array(hashtags).T):
    gal[x,y] = i + 1

In [45]:
hashtags

(array([ 0,  1,  2,  5,  6,  7, 10, 11, 11], dtype=int64),
 array([ 4,  9,  0,  8,  1, 12,  9,  0,  5], dtype=int64))

In [46]:
from scipy.spatial.distance import cityblock

In [ ]:
def get_coords(where):
    coords = []
    for x,y in zip(where[0], where[1]):
        coords.append([x,y])
    return coords

In [48]:
coords = []
for x,y in zip(hashtags[0], hastags[1]):
    coords.append([x,y])

In [53]:
total = 0
for i, c1 in enumerate(coords):
    for j, c2 in enumerate(coords[i+1:]):
        total += cityblock(c1,c2)

In [60]:
np.repeat(np.reshape(text[3, :], (1,10)), 2, axis = 0)

array([['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [54]:
total

374

In [ ]:
for x,y in hashtags:


In [39]:
gal

array([['.', '.', '.', '.', '1', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '2', '.', '.', '.'],
       ['3', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '4', '.', '.', '.', '.'],
       ['.', '5', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '6'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '7', '.', '.', '.'],
       ['8', '.', '.', '.', '.', '9', '.', '.', '.', '.', '.', '.', '.']],
      dtype='<U1')

In [13]:
d = text[cols[0], :]

In [14]:
np.insert(text, cols, d, axis=1)

ValueError: shape mismatch: value array of shape (10,) could not be broadcast to indexing result of shape (10,2)

In [18]:
np.insert(text, cols, d, axis = 0)

array([['.', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.'],
       ['.', '#', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '#'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '#', '.', '.', '.', '.', '.']], dtype='<U1')

In [15]:
cols

[3, 7]

In [11]:
np.vstack(text[:cols+1, :], d, )

array([['.', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '#', '.', '.'],
       ['#', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [6]:
rows

[2, 5, 8]

In [25]:

gal = text.copy()
hastags = np.where(text == '#')
for i, (x, y) in enumerate(np.array(hastags).T):
    gal[x,y] = i

In [27]:
gal

array([['.', '.', '.', '0', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '1', '.', '.'],
       ['2', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '3', '.', '.', '.'],
       ['.', '4', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '5'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '6', '.', '.'],
       ['7', '.', '.', '.', '8', '.', '.', '.', '.', '.']], dtype='<U1')

Keep

In [1]:
def hyperlink_markdown(path, done, begin = 1, end = 26):

    hyperlinks = ''

    for num in range(begin, end):
        if num in done:
            hyperlinks += f'[**]({path}{num:02d}.py) |'
        else:
            hyperlinks += f'[X]({path}{num:02d}.py) |'

    return hyperlinks

path = 'https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day'
hyperlink_markdown(path, done = [1,2,3,4,6,7], begin = 1, end = 26)

'[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day01.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day02.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day03.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day04.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day05.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day06.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day07.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day08.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day09.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day10.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day11.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day12.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day13.py) |[X](https://github

In [2]:
def table_formatter(begin = 1, end = 26):

    table_line = ''
    for  i in range(begin, end):
        table_line += f':-----:|'

    return table_line

table_formatter(1, 26)

':-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|'

In [2]:
import os
import shutil

In [9]:
os.listdir()

['aoc',
 'day01.py',
 'day04.py',
 'day05.ipynb',
 'day05.py',
 'day06.py',
 'day07.py',
 'input',
 'notebook.ipynb']

In [4]:
src = 'day11.py'
for i in range(12,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [11]:
src = 'day01.py'
for i in range(8,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [12]:
src = 'input/day01_example.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [13]:
src = 'input/day01_example.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [14]:
src = 'input/day01_input.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)

In [15]:
src = 'input/day01_input.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)