In [2]:
from aoc import results, read_txt, remove_empty
import os
from glob import glob
import numpy as np

In [3]:
day = 'day12'

path = f'input/{day}'

files = glob(f'{path}*')
file = files[0]


In [4]:
file

'input\\day12_example.txt'

In [5]:
text = read_txt(file)

In [7]:
line = text[0]

In [17]:
v, n = line.split(' ')

In [18]:
n = np.asarray(n.split(',')).astype(int)
n

array([1, 1, 3])

In [27]:
qms = np.where(np.array([*v]) == '?')

In [37]:
a = np.zeros(np.array([*v]).shape) + (np.array([*v]) == '#')

In [39]:
a[qms] = 1

In [86]:
def binary_to_string(bin):
    key = ['.', '#']
    new = [key[int(i)] for i in bin]
    return ''.join(new)

In [91]:
def get_sets(string):
    q = str(string).split('.')
    lens = [len(qi) for qi in q if len(qi) != 0]
    return lens

In [92]:
import itertools

In [106]:
def get_line_val(line):
    v, n = line.split(' ')
    n = np.asarray(n.split(',')).astype(int)
    n = list(n)
    qms = np.where(np.array([*v]) == '?')
    reps = len(qms[0])
    lst = list(itertools.product([0, 1], repeat=reps))
    array =  np.zeros(np.array([*v]).shape) + (np.array([*v]) == '#')
    total = 0
    for li in lst:
        array[qms] = np.array(li)
        set_c = get_sets(binary_to_string(array))
        if set_c == n:
            total += 1
    return total


In [114]:
second = 1

In [139]:
v, n = line.split(' ')
n = np.asarray(n.split(',')).astype(int)

if second:
    v = '?'.join([v]*5)
n = list(n)*5 if second else list(n)

qms = np.where(np.array([*v]) == '?')
reps = len(qms[0])
lst = list(itertools.product([0, 1], repeat=reps))
array =  np.zeros(np.array([*v]).shape) + (np.array([*v]) == '#')
total = 0
for li in lst:
    array[qms] = np.array(li)
    set_c = get_sets(binary_to_string(array))
    if set_c == n:
        total += 1

'???.###????.###????.###????.###????.###'

In [134]:
n

[1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3]

In [116]:

n

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3]

In [112]:
np.repeat(n, 5)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3])

In [108]:
asum([get_line_val(line) for line in text])

21

In [ ]:
total = 0
for line in text:
    total += get_line_val(a)

In [107]:
get_line_val(line)

1

In [104]:
qms

(array([0, 1, 2], dtype=int64),)

In [102]:
n

[1, 1, 3]

In [103]:
lst

[(0,), (1,)]

In [100]:
set_c

[3, 3]

In [99]:
n

[1, 1, 3]

In [95]:
n

1

In [82]:
li

(1, 1, 1)

In [ ]:
l

In [64]:
si = get_sets(binary_to_string(a))
si

[3, 3]

In [48]:
new

['#', '#', '#', '.', '#', '#', '#']

In [ ]:
s = ''
for i in range(len(s)):
    if i in qms:
        s.append('#')


In [29]:
t = v

TypeError: 'str' object does not support item assignment

Keep

In [1]:
def hyperlink_markdown(path, done, begin = 1, end = 26):

    hyperlinks = ''

    for num in range(begin, end):
        if num in done:
            hyperlinks += f'[**]({path}{num:02d}.py) |'
        else:
            hyperlinks += f'[X]({path}{num:02d}.py) |'

    return hyperlinks

path = 'https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day'
hyperlink_markdown(path, done = [1,2,3,4,6,7], begin = 1, end = 26)

'[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day01.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day02.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day03.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day04.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day05.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day06.py) |[**](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day07.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day08.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day09.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day10.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day11.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day12.py) |[X](https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day13.py) |[X](https://github

In [2]:
def table_formatter(begin = 1, end = 26):

    table_line = ''
    for  i in range(begin, end):
        table_line += f':-----:|'

    return table_line

table_formatter(1, 26)

':-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|'

In [2]:
import os
import shutil

In [9]:
os.listdir()

['aoc',
 'day01.py',
 'day04.py',
 'day05.ipynb',
 'day05.py',
 'day06.py',
 'day07.py',
 'input',
 'notebook.ipynb']

In [4]:
src = 'day11.py'
for i in range(12,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [11]:
src = 'day01.py'
for i in range(8,26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [12]:
src = 'input/day01_example.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [13]:
src = 'input/day01_example.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [14]:
src = 'input/day01_input.txt'
for i in range(2,4):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)

In [15]:
src = 'input/day01_input.txt'
for i in range(8,26):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)