In [1]:
from aoc import results, read_txt, remove_empty, load_text
import numpy as np

# 18

In [53]:
day = 'day18'
text = load_text(day, num=0)

Result of Advent of Code, year 2023, day 18
Find description at https://adventofcode.com/2023/day/18

input\day18_example.txt


In [62]:
def next_pos(pos, d):

    new_pos = pos + dir_to_step[d]
    return new_pos

In [105]:
dir_to_step = {'R': np.array([0, 1]),
               'L': np.array([0, -1]),
               'U': np.array([-1, 0]),
               'D': np.array([1, 0]),
               '0': np.array([0, 1]),
               '1': np.array([0, -1]),
               '2': np.array([-1, 0]),
               '3': np.array([1, 0]),
               }

next_dir = {'right': {'right': 'down',
                      'straight': 'right',
                      'left': 'up',
                      },
            'left': {'right': 'up',
                     'straight': 'left',
                     'left': 'down',
                     },
            'down': {'right': 'left',
                     'straight': 'down',
                     'left': 'right',
                     },
            'up': {'right': 'right',
                   'straight': 'up',
                   'left': 'left',
                   },
            }

In [64]:
text

['R 6 (#70c710)',
 'D 5 (#0dc571)',
 'L 2 (#5713f0)',
 'D 2 (#d2c081)',
 'R 2 (#59c680)',
 'D 2 (#411b91)',
 'L 5 (#8ceee2)',
 'U 2 (#caa173)',
 'L 1 (#1b58a2)',
 'U 2 (#caa171)',
 'R 2 (#7807d2)',
 'U 3 (#a77fa3)',
 'L 2 (#015232)',
 'U 2 (#7a21e3)']

In [82]:
all_pos = []
pos = np.array([0,0])
all_pos.append(pos)
max_x = 0
max_y = 0
for l in text:
    t, v, c = l.split(' ')

    for i in range(int(v)):
        pos = next_pos(pos, t)
        all_pos.append(pos)



In [95]:
miny, minx = np.min(np.array(all_pos), axis = 0)
maxy, maxx = np.max(np.array(all_pos), axis = 0)
board = np.zeros((maxy-miny + 1, maxx - minx + 1))

for pos in all_pos:
    board[pos[0] - miny, pos[1] - minx] = 1

In [102]:
t = c[2:-2]
v = c[-2]

In [110]:
int(t, 16)

500254

In [107]:
dir_to_step[v]

array([1, 0])

In [104]:
v

'3'

In [103]:
t

'7a21e'

In [91]:
board[np.array(all_pos)] = 1

In [92]:
board

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [76]:
board = np.zeros((max_y+ 1, max_x+ 1))


In [79]:
board = scipy.ndimage.binary_fill_holes(board)

In [81]:
np.sum(board)

62

In [68]:
all_pos

[array([0, 0]),
 array([0, 1]),
 array([0, 2]),
 array([0, 3]),
 array([0, 4]),
 array([0, 5]),
 array([0, 6]),
 array([1, 6]),
 array([2, 6]),
 array([3, 6]),
 array([4, 6]),
 array([5, 6]),
 array([5, 5]),
 array([5, 4]),
 array([6, 4]),
 array([7, 4]),
 array([7, 5]),
 array([7, 6]),
 array([8, 6]),
 array([9, 6]),
 array([9, 5]),
 array([9, 4]),
 array([9, 3]),
 array([9, 2]),
 array([9, 1]),
 array([8, 1]),
 array([7, 1]),
 array([7, 0]),
 array([6, 0]),
 array([5, 0]),
 array([5, 1]),
 array([5, 2]),
 array([4, 2]),
 array([3, 2]),
 array([2, 2]),
 array([2, 1]),
 array([2, 0]),
 array([1, 0]),
 array([0, 0])]

In [60]:
v

'6'

# 17

In [4]:
day = 'day17'
text = load_text(day, num=0)

Result of Advent of Code, year 2023, day 17
Find description at https://adventofcode.com/2023/day/17

input\day17_example.txt


In [9]:
dir_to_step = {'right': np.array([0, 1]),
               'left': np.array([0, -1]),
               'up': np.array([-1, 0]),
               'down': np.array([1, 0]),
               }

next_dir = {'right': {'right': 'down',
                      'straight': 'right',
                      'left': 'up',
                      },
            'left': {'right': 'up',
                     'straight': 'left',
                     'left': 'down',
                     },
            'down': {'right': 'left',
                     'straight': 'down',
                     'left': 'right',
                     },
            'up': {'right': 'right',
                   'straight': 'up',
                   'left': 'left',
                   },
            }

In [10]:
def to_array(m):
    mlist = []
    for mi in m:
        mlist.append([*mi])

    return np.asarray(mlist)

In [22]:
def calc_loss(block, pos, end_point, d, n_straight, visited):
    visited_from_here = visited.copy()
    h, w = block.shape

    visited_from_here[pos[0], pos[1]] = 1
    val = block[pos[0], pos[1]]

    if np.sum(pos != end_point) == 0:
        return val, visited_from_here
    else:
        v = []
        vfh = []
        dn = next_dir[d]['right']
        new_pos = pos + dir_to_step[dn]
        if 0 <= new_pos[0] < h and new_pos[1] >= 0 and new_pos[1] < w:

            if not visited[new_pos[0], new_pos[1]]:
                vt, vh = calc_loss(block, new_pos, end_point, dn, 0, visited_from_here)
                if vt != None:
                    v.append(vt)
                    vfh.append(vh)

        dn = next_dir[d]['left']
        new_pos = pos + dir_to_step[dn]
        if 0 <= new_pos[0] < h and new_pos[1] >= 0 and new_pos[1] < w:

            if not visited[new_pos[0], new_pos[1]]:
                vt, vh = calc_loss(block, new_pos, end_point, dn, 0, visited_from_here)
                if vt != None:
                    v.append(vt)
                    vfh.append(vh)

        if n_straight < 3:
            dn = next_dir[d]['straight']
            new_pos = pos + dir_to_step[dn]
            if 0 <= new_pos[0] < h and new_pos[1] >= 0 and new_pos[1] < w:

                if not visited[new_pos[0], new_pos[1]]:
                    vt, vh = calc_loss(block, new_pos, end_point, dn, n_straight + 1, visited_from_here)
                    if vt != None:
                        v.append(vt)
                        vfh.append(vh)

    if v == []:
        val = None
    else:

        val += np.min(v)
        visited_from_here = vfh[np.argmin(v)]

    return val, visited_from_here

In [23]:
block = to_array(text).astype(int)
pos = np.array([0, 0])
loss = 0
end_point = np.array(block.shape) - np.array([1, 1])
n_straight = 0
dirs = ['right', 'down']
visited = np.zeros_like(block)
vs = []
for d in dirs:
    visited_from_here = visited.copy()
    val, visited_from_here = calc_loss(block, pos, end_point, d, n_straight, visited_from_here)
    if val:
        vs.append(val)


KeyboardInterrupt: 

In [86]:
visited_from_here

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Dijkstra

In [38]:
block = to_array(text).astype(int)

In [39]:
def feas(p, h, w):
    feasible = True if (0 <= p[0] < h and p[1] >= 0 and p[1] < w) else False
    return feasible



In [50]:
def get_graph(block):
    h, w = block.shape
    g = {}
    for i in range(h):
        for j in range(w):
            positions = []
            p1 = i - 1, j
            if feas(p1, h, w):
                positions.append([p1[0] * h + p1[1], block[p1[0], p1[1]], 'left'])
            p2 = i, j - 1
            if feas(p2, h, w):
                positions.append([p2[0] * h + p2[1], block[p2[0], p2[1]], 'up'])
            p3 = i + 1, j
            if feas(p3, h, w):
                positions.append([p3[0] * h + p3[1], block[p3[0], p3[1]], 'right'])
            p4 = i, j + 1
            if feas(p4, h, w):
                positions.append([p4[0] * h + p4[1], block[p4[0], p4[1]], 'down'])
            g[i*h+j] = positions
    return g

In [51]:
g = get_graph(block)

In [52]:
g

{0: [[13, 3, 'right'], [1, 4, 'down']],
 1: [[0, 2, 'up'], [14, 2, 'right'], [2, 1, 'down']],
 2: [[1, 4, 'up'], [15, 1, 'right'], [3, 3, 'down']],
 3: [[2, 1, 'up'], [16, 5, 'right'], [4, 4, 'down']],
 4: [[3, 3, 'up'], [17, 4, 'right'], [5, 3, 'down']],
 5: [[4, 4, 'up'], [18, 5, 'right'], [6, 2, 'down']],
 6: [[5, 3, 'up'], [19, 3, 'right'], [7, 3, 'down']],
 7: [[6, 2, 'up'], [20, 5, 'right'], [8, 1, 'down']],
 8: [[7, 3, 'up'], [21, 3, 'right'], [9, 1, 'down']],
 9: [[8, 1, 'up'], [22, 5, 'right'], [10, 3, 'down']],
 10: [[9, 1, 'up'], [23, 6, 'right'], [11, 2, 'down']],
 11: [[10, 3, 'up'], [24, 2, 'right'], [12, 3, 'down']],
 12: [[11, 2, 'up'], [25, 3, 'right']],
 13: [[0, 2, 'left'], [26, 3, 'right'], [14, 2, 'down']],
 14: [[1, 4, 'left'], [13, 3, 'up'], [27, 2, 'right'], [15, 1, 'down']],
 15: [[2, 1, 'left'], [14, 2, 'up'], [28, 5, 'right'], [16, 5, 'down']],
 16: [[3, 3, 'left'], [15, 1, 'up'], [29, 5, 'right'], [17, 4, 'down']],
 17: [[4, 4, 'left'], [16, 5, 'up'], [30, 2

In [49]:
naive_dijkstras(g, 0)[-1]

78

In [30]:
graph = {
    0: [(1, 1)],
    1: [(0, 1), (2, 2), (3, 3)],
    2: [(1, 2), (3, 1), (4, 5)],
    3: [(1, 3), (2, 1), (4, 1)],
    4: [(2, 5), (3, 1)]
}

In [35]:
from numpy import Inf

In [36]:
# takes the graph and the starting node
# returns a list of distances from the starting node to every other node
def naive_dijkstras(graph, root):
    n = len(graph)
    # initialize distance list as all infinities
    dist = [Inf for _ in range(n)]
    # set the distance for the root to be 0
    dist[root] = 0
    # initialize list of visited nodes
    visited = [False for _ in range(n)]
    # loop through all the nodes
    for _ in range(n):
        # "start" our node as -1 (so we don't have a start node yet)
        u = -1
        # loop through all the nodes to check for visitation status
        for i in range(n):
            # if the node 'i' hasn't been visited and
            # we haven't processed it or the distance
            #
            # dist[u]):
                u = i
        # all the nodes have been visited or we can't reach this node
        if dist[u] == Inf:
            break
        # set the node as visited
        visited[u] = True
        # compare the distance to each node from the "start" node
        # to the distance we currently have on file for it
        for v, l in graph[u]:
            if dist[u] + l < dist[v]:
                dist[v] = dist[u] + l
    return dist

In [37]:
naive_dijkstras(graph, 0)

[0, 1, 3, 4, 5]

a# day 13

In [ ]:
day = 'day13'
text = load_text(day, num=0)

In [ ]:
def split_maps(text):
    all = []
    cur = []
    for line in text:
        if line == '':
            all.append(cur.copy())
            cur = []
        else:
            cur.append(line)
    all.append(cur)
    return all


def to_array(m):
    mlist = []
    for mi in m:
        mlist.append([*mi])

    return np.asarray(mlist)


def vertical_mirror(ti_map):
    idx = 0
    h, w = ti_map.shape
    for i in range(2, h - 1):

        left = np.flip(ti_map[:i, :], axis=0)
        right = ti_map[i:, :]

        hl, wl = left.shape
        hr, wr = right.shape

        if hl > hr:
            m = hr
        else:
            m = hl

        # print('left:', left[:,:m])
        # print('right:',right[:,:m])
        if np.array_equal(left[:m, :], right[:m, :]):
            idx = i
        #ti_map[:i] == np.flip(ti_map[i:np.min([i+i, h)])
    return idx * 100


def horizontal_mirror(ti_map):
    idx = 0
    h, w = ti_map.shape
    for i in range(2, w - 1):

        left = np.flip(ti_map[:, :i], axis=1)
        right = ti_map[:, i:]

        hl, wl = left.shape
        hr, wr = right.shape

        if wl > wr:
            m = wr
        else:
            m = wl

        # print('left:', left[:,:m])
        # print('right:',right[:,:m])
        if np.array_equal(left[:, :m], right[:, :m]):
            idx = i
            print(left[:, :m], right[:, :m])
        #ti_map[:i] == np.flip(ti_map[i:np.min([i+i, h)])
    return idx

In [ ]:
text = load_text(day, num=1)

In [ ]:
a = np.ones((10, 10))
b = np.ones((10, 5))
if not b.shape > a.shape:
    a[b.shape]

In [ ]:
a

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
a.shape > b.shape

In [ ]:
a

In [ ]:
b

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
a = torch.tensor(np.random.randint(5, 8, (20, 20)) * .1)

In [ ]:
q = F.normalize(a)

In [ ]:
(a - a.mean()) / a.std()

In [ ]:
q.max()

In [ ]:
q.min()

In [ ]:
text

In [ ]:
maps = split_maps(text)
total = 0
for m in maps:
    ti_map = to_array(m)
    val = vertical_mirror(ti_map)
    val += horizontal_mirror(ti_map)
    total += val

In [ ]:
m

In [ ]:
m = maps[2]
ti_map = to_array(m)
print(vertical_mirror(ti_map))
print(horizontal_mirror(ti_map))

In [ ]:
m

In [ ]:

total

In [ ]:
total

In [ ]:
text

In [ ]:
def get_sets(p):
    string = ''.join(p)
    q = str(string).split('.')
    lens = [len(qi) for qi in q if len(qi) != 0]
    return lens


def rec(p, n, qms, c):
    global tdict

    if c != len(qms):
        gsets = get_sets(p[:qms[c]])
        #print(gsets, p[:qms[c]])
        if str(gsets) + ',' + str(c) in tdict.keys():
            if c != 0:
                return tdict[str(gsets) + ',' + p[qms[c - 1]] + ',' + str(c)]
            else:
                return tdict[str(gsets) + ',' + str(c)]
        else:
            t1 = p.copy()
            t1[qms[c]] = '#'
            t2 = p.copy()
            t2[qms[c]] = '.'

            a1 = rec(t1, n, qms, c + 1)
            a2 = rec(t2, n, qms, c + 1)
            val = a1 + a2
            if c != 0:
                key = str(gsets) + ',' + p[qms[c - 1]] + ',' + str(c)
            else:
                key = str(gsets) + ',' + str(c)
            tdict[key] = val
            return val
    else:
        if np.array_equal(np.array(get_sets(p)), n):
            key = str(get_sets(p)) + ',' + p[qms[c - 1]] + ',' + str(c)
            tdict[key] = 1
            return 1
        else:
            key = str(get_sets(p)) + ',' + p[qms[c - 1]] + ',' + str(c)
            tdict[key] = 0
            return 0


def get_line_val(line, second):
    global tdict
    tdict = {}

    v, n = line.split(' ')
    n = np.asarray(n.split(',')).astype(int)
    if second:
        v = '?'.join([v] * 5)

    n = list(n) * 5 if second else list(n)
    qms = np.where(np.array([*v]) == '?')

    total = rec(np.array([*v]), n, qms[0], 0)

    return total


def get_value(text, second):
    val = np.sum([get_line_val(line, second) for line in text])

    return val

In [ ]:
get_line_val(line, 0)

In [ ]:
get_value(text, 0)

In [ ]:
tdict

In [ ]:
aline

In [ ]:
line

In [ ]:
tdict

In [ ]:
dict

In [ ]:
line = text[0];
line

In [ ]:
tdict

Keep

In [ ]:
def hyperlink_markdown(path, done, begin=1, end=26):
    hyperlinks = ''

    for num in range(begin, end):
        if num in done:
            hyperlinks += f'[**]({path}{num:02d}.py) |'
        else:
            hyperlinks += f'[X]({path}{num:02d}.py) |'

    return hyperlinks


path = 'https://github.com/FrankNicoMol/AdventOfCode/blob/main/2023/day'
hyperlink_markdown(path, done=[1, 2, 3, 4, 6, 7], begin=1, end=26)

In [ ]:
def table_formatter(begin=1, end=26):
    table_line = ''
    for i in range(begin, end):
        table_line += f':-----:|'

    return table_line


table_formatter(1, 26)

In [ ]:
import os
import shutil

In [ ]:
os.listdir()

In [ ]:
src = 'day13.py'
for i in range(14, 26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [ ]:
src = 'day01.py'
for i in range(8, 26):
    dst = f'day{i:02d}.py'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_example.txt'
for i in range(2, 4):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_example.txt'
for i in range(8, 26):
    dst = f'input/day{i:02d}_example.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_input.txt'
for i in range(2, 4):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)

In [ ]:
src = 'input/day01_input.txt'
for i in range(8, 26):
    dst = f'input/day{i:02d}_input.txt'
    shutil.copyfile(src, dst)